#!/bin/bash

set -e

if [ -n "$NOTPARALLEL" ] ; then
	export MAKEFLAGS="$MAKEFLAGS -j 1"
fi

if [ -z "$configure" ] ; then
	configure=./configure
fi

set -vx

if [ -x autogen.sh ] ; then
	NOCONFIGURE=1 ./autogen.sh
elif [ ! -x configure ] ; then
	autoreconf -if
fi

$configure "$@"
make
make install -j 1
