#!/bin/bash

set -evx

if [ -x autogen.sh ] ; then
	NOCONFIGURE=1 ./autogen.sh
elif [ ! -x configure ] ; then
	autoreconf -if
fi

if [ -z "$configure" ] ; then
	configure=./configure
fi

$configure "$@"
make
make install
